import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { CodeSnippet } from './openai';

/**
 * Creates a README.md file with setup instructions based on code snippets
 */
function generateReadme(snippets: CodeSnippet[], projectName: string): string {
  // Get unique languages in the project
  const languages = new Set<string>();
  const filesByExtension: Record<string, string[]> = {};
  
  snippets.forEach(snippet => {
    const extension = snippet.filename.split('.').pop()?.toLowerCase() || '';
    languages.add(snippet.language.toLowerCase());
    
    if (!filesByExtension[extension]) {
      filesByExtension[extension] = [];
    }
    filesByExtension[extension].push(snippet.filename);
  });
  
  // Determine project type
  let projectType = 'General';
  let setupInstructions = '';
  
  // Check for common project patterns
  const hasHTML = filesByExtension['html']?.length > 0;
  const hasJS = filesByExtension['js']?.length > 0;
  const hasCSS = filesByExtension['css']?.length > 0;
  const hasPackageJSON = snippets.some(s => s.filename === 'package.json');
  const hasPython = filesByExtension['py']?.length > 0;
  const hasJava = filesByExtension['java']?.length > 0;
  
  // Check for environment dependencies
  const envInstructions = `
## Environment Setup

This project includes an \`.env.example\` file with required environment variables.
To set up your environment:

1. Copy the \`.env.example\` file to a new file named \`.env\`
\`\`\`bash
cp .env.example .env
\`\`\`

2. Edit the \`.env\` file and fill in your actual values for each environment variable
\`\`\`
# Edit the .env file with your actual values
EXAMPLE_API_KEY="your-actual-api-key"
\`\`\`
`;
  
  if (hasHTML && (hasJS || hasCSS)) {
    projectType = 'Web';
    setupInstructions = `
## Setup Instructions

1. Extract all files to a directory
2. Open the HTML file in your browser:
   - Double-click the HTML file, or
   - Right-click the HTML file and select "Open with" your preferred browser

For development with live reload, you can use tools like:
- Live Server extension for VS Code
- Python's built-in server: \`python -m http.server\`
- Node.js's http-server: \`npx http-server .\`
`;
  } else if (hasPackageJSON) {
    projectType = 'Node.js';
    setupInstructions = `
## Setup Instructions

1. Extract all files to a directory
2. Open a terminal in that directory
3. Set up environment variables (see Environment Setup section below)
4. Install dependencies:
\`\`\`bash
npm install
\`\`\`
5. Run the application:
\`\`\`bash
npm start
\`\`\`

If the start script is not defined in package.json, try:
\`\`\`bash
node index.js
\`\`\` 
or the name of your main JavaScript file.
`;
  } else if (hasPython) {
    projectType = 'Python';
    setupInstructions = `
## Setup Instructions

1. Extract all files to a directory
2. Open a terminal in that directory
3. Set up environment variables (see Environment Setup section below)
4. Create a virtual environment (optional but recommended):
\`\`\`bash
python -m venv venv
\`\`\`
5. Activate the virtual environment:
   - Windows: \`venv\\Scripts\\activate\`
   - macOS/Linux: \`source venv/bin/activate\`
6. Install required packages (if requirements.txt exists):
\`\`\`bash
pip install -r requirements.txt
\`\`\`
7. Run the main script:
\`\`\`bash
python ${filesByExtension['py']?.[0] || 'main.py'}
\`\`\`
`;
  } else if (hasJava) {
    projectType = 'Java';
    setupInstructions = `
## Setup Instructions

1. Extract all files to a directory
2. Open a terminal in that directory
3. Set up environment variables (see Environment Setup section below)
4. Compile the Java files:
\`\`\`bash
javac *.java
\`\`\`
5. Run the main class:
\`\`\`bash
java Main
\`\`\`
Replace 'Main' with the actual name of your main class.
`;
  } else {
    // Generic instructions for other project types
    setupInstructions = `
## Setup Instructions

This project contains the following file types:
${Object.entries(filesByExtension)
  .map(([ext, files]) => `- ${ext.toUpperCase()}: ${files.length} file(s)`)
  .join('\n')}

### General setup:
1. Extract all files to a directory
2. Open the files in your preferred IDE or editor
3. Set up environment variables (see Environment Setup section below)
4. Run the code according to your language's standard practices
`;
  }

  return `# ${projectName}

Generated by CodeCraft AI on ${new Date().toLocaleDateString()}

This project contains ${snippets.length} file(s) across ${languages.size} language(s).

## Files
${snippets.map(s => `- ${s.filename}`).join('\n')}

${setupInstructions}

${envInstructions}

## Additional Notes
- This code was automatically generated and may require modifications to work in your specific environment
- The \`.env.example\` file includes sample environment variables detected based on your code
- Feel free to modify and extend this code for your needs
`;
}

/**
 * Generate an example .env file
 */
function generateEnvFile(snippets: CodeSnippet[]): string {
  // Detect if project needs specific environment variables
  const fileNames = snippets.map(s => s.filename.toLowerCase());
  const fileContents = snippets.map(s => s.code.toLowerCase());
  
  // Default environment variables
  const envVars = [
    '# Server Configuration',
    'PORT=5000',
    'HOST="0.0.0.0"',
    'NODE_ENV="development"'
  ];
  
  // Check for database usage
  const needsDatabase = fileContents.some(content => 
    content.includes('database') || 
    content.includes('postgresql') || 
    content.includes('postgres') ||
    content.includes('mongodb') ||
    content.includes('mongoose') ||
    content.includes('sequelize') ||
    content.includes('prisma')
  );
  
  if (needsDatabase) {
    envVars.unshift('', '# Database connection');
    envVars.unshift('DATABASE_URL="postgresql://postgres:password@localhost:5432/mydb"');
  }
  
  // Check for OpenAI API usage
  const needsOpenAI = fileContents.some(content => 
    content.includes('openai') || 
    content.includes('gpt')
  );
  
  if (needsOpenAI) {
    envVars.unshift('', '# OpenAI API Configuration');
    envVars.unshift('OPENAI_BASE_URL="https://api.openai.com/v1" # Default OpenAI API URL - change if using a proxy');
    envVars.unshift('OPENAI_API_KEY="your-openai-api-key"');
  }
  
  // Check for authentication needs
  const needsAuth = fileContents.some(content => 
    content.includes('jwt') || 
    content.includes('auth') || 
    content.includes('session') ||
    content.includes('token')
  );
  
  if (needsAuth) {
    envVars.unshift('', '# Authentication');
    envVars.unshift('JWT_SECRET="your-jwt-secret-key"');
    envVars.unshift('SESSION_SECRET="your-session-secret"');
  }
  
  return envVars.join('\n');
}

/**
 * Exports all code snippets as a project zip file
 */
export async function exportProject(
  snippets: CodeSnippet[], 
  projectName: string = 'codecraft-project'
): Promise<void> {
  if (!snippets || snippets.length === 0) {
    throw new Error('No code snippets to export');
  }
  
  try {
    const zip = new JSZip();
    
    // Add README file
    const readme = generateReadme(snippets, projectName);
    zip.file('README.md', readme);
    
    // Add .env.example file
    const envFile = generateEnvFile(snippets);
    zip.file('.env.example', envFile);
    
    // Add all code snippets
    snippets.forEach(snippet => {
      zip.file(snippet.filename, snippet.code);
    });
    
    // Generate the zip file
    const content = await zip.generateAsync({ type: 'blob' });
    
    // Save the zip file
    saveAs(content, `${projectName}.zip`);
    
    return Promise.resolve();
  } catch (error) {
    console.error('Error creating project export:', error);
    return Promise.reject(error);
  }
}